# 7장 에러 처리

> 이 글은 클린코드: 애자일 소프트웨어 장인 정신(로버트 C.마틴)을 참고하여 정리한 것입니다.

이 장에서는 에러를 깔끔하게 처리하는 법을 다룬다. 이를 위해서는 error code를 사용하는 것보다 exception을 사용하는 것이 좋다. 더 나아가 아예 에러 처리가 필요없도록 하는 special case pattern도 매우 유용한 기술이다.

### 에러 코드보다 예외를 사용하라

```java
public class DeviceController {
    ...
    public void sendShutDown() {
        DeviceHandle handle = getHandle(DEV1);
        // Check the state of the device
        if (handle != DeviceHandle.INVALID) {
            // Save the device status to the record field
            DeviceRecord record = retrieveDeviceRecord(handle);
            // If not suspended, shut down
            if (record.getStatus() != DEVICE_SUSPENDED) {
                pauseDevice(handle);
                clearDeviceWorkQueue(handle);
                closeDevice(handle);
            } else {
                logger.log("Device suspended. Unable to shut down");
            }
        } else {
            logger.log("Invalid handle for: " + DEV1.toString());
        }
    }
    ...
}
```

이러한 방법을 사용하면 calling code가 복잡해진다. 호출한 즉시 오류를 확인해야 하기 때문이다.<br>오류가 발생하면 throw exception하는 것이 낫다. 그러면 로직과 error handling 코드가 섞이지 않으므로 코드가 깔끔해진다.

```java
public class DeviceController {
    ...
    public void sendShutDown() {
        try {
            tryToShutDown();
        } catch (DeviceShutDownError e) {
            logger.log(e);
        }
    }

    private void tryToShutDown() throws DeviceShutDownError {
        DeviceHandle handle = getHandle(DEV1);
        DeviceRecord record = retrieveDeviceRecord(handle);

        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
    }

    private DeviceHandle getHandle(DeviceID id) {
        ...
        throw new DeviceShutDownError("Invalid handle for: " + id.toString());
        ...
    }
    ...
}
```

훨씬 깔끔해진 코드이다. 디바이스를 종료하는 로직과 error handling 로직을 분리하였기 때문에 이제 각 개념을 독립적으로 보고 이해할 수 있다.

### try-catch-finally문을 먼저 작성하라

예외가 발생하는 코드를 짤 때는 try-catch-finally문으로 시작하는 편이 낫다. 그러면 try블록에서 무슨 일이 생기든지 호출자가 기대하는 상태를 정의하기 쉬워진다.

```
try {

    // do something

} catch (XXXException e) {
    // handle XXXException
} catch (YYYException e) {
    // handle YYYException
} finally {
    // clean up
}
```

### 예외에 context를 제공해라

각 예외는 충분한 의미(context)를 제공해야 한다. 그러면 오류가 발생한 원인과 위치를 찾기 쉬워진다. Java는 모든 예외에 호출 스택을 제공한다. 하지만 실패한 코드의 의도를 파악하려면 호출 스택만으로 부족하다.<br>
실패한 연산 이름과 실패 유형 등의 정보를 담아 예외와 함께 던진다.

- 예시

```java
public static void main(String[] args) {
    Scanner inputScanner= new Scanner(System.in);
    intfirstNumber, secondNumber, result;

    firstNumber= inputScanner.nextInt();
    secondNumber= inputScanner.nextInt();
    inputScanner.close();
    try {
        result = divideInt(firstNumber, secondNumer);
    } catch (DivideByZeroException e) {
        System.out.println(e.getMessage());
    }
}

public static int divideInt(int dividend, int divisor) {
    if (divisor == 0)
        throw new DivideByZeroException(“divideInt(): divisor cannot be 0”);
    return dividend / divisor;
}
```

`divideInt`함수에서 던지는 `DivideByZeroException` 예외에서 제공하는 정보는 충분한 정보를 제공하고 있다.

### 호출자를 고려해 예외 클래스를 정의하라

다르게 처리하고 싶을 때만 다른 예외 클래스를 사용하라는 것이다.

- 예시: excpetion의 나쁜 분류

```
ACMEPortport = new ACMEPort(12);

try {
    port.open();
} catch (DeviceResponseException e) {
    reportPortError(e);
    logger.log("Device response exception", e);
} catch (ATM121UnlockedException e) {
    reportPortError(e);
    logger.log("Unlock exception", e);
} catch (GMXError e) {
    reportPortError(e);
    logger.log("Device response exception");
}
```

ACMEPort는 third-party 라이브러리이다. 이 코드에서는 라이브러리에서 던질 예외를 모두 잡아낸다. 이 코드에는 reportPortError와 같이 중복이 많다!

- 예시: 개선시킨 코드

```
LocalPortport = new LocalPort(12);

try {
    port.open();
} catch (PortDeviceFailure e) {
    reportError(e);
    logger.log(e.getMessage(), e);
}

```

```
public class LocalPort{
    private ACMEPort innerPort;

    public LocalPort(int portNumber) {
        innerPort = new ACMEPort(portNumber);
    }

    public void open() {
        try {
            innerPort.open();
        } catch (DeviceResponseException e) {
            throw new PortDeviceFailure(e);
        } catch (ATM121UnlockedException e) {
            throw new PortDeviceFailure(e);
        } catch (GMXError e) {
            throw new PortDeviceFailure(e);
        }
    }
    ...
}
```

ACMEPort에 대한 wrapper class인 LocalPort를 생성하였다. LocalPort의 open()에서는 실제 ACMEPort의 open() 연산이 행해진다.<br>
port device의 실패에 대한 예외 유형은 하나만 정의하였다. 그랬더니 프로그램이 훨씬 깨끗해졌다.<br>
함수의 이름, argument, return 타입 또는 exception의 유형을 바꾸고 싶다면 외부 API를 Wrapping하는 것이 최선의 방법이다.

- 외부 API Wrapping의 장점
  - 외부 라이브러리와 프로그램 사이의 의존성이 크게 줄어든다.
  - 나중에 다른 라이브러리로 교체해도 비용이 적다.
  - 또한 특정 vendor의 API 설계 방식에 묶이지 않는다. 프로그램이 사용하기 편리한 API를 정의할 수 있다.

### Normal Flow를 정의하라

몇몇 프로그래머들은 special case를 처리하기 위해 catch문을 사용한다. 아래의 예시를 보자.

- 예시: 비용 청구 어플리케이션에서 사원 식비의 총계를 계산하는 '허술한' 코드

```
try {
    MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
    m_total += expenses.getTotal();
} catch(MealExpensesNotFound e) {
    m_total += getMealPerDiem();
}
```

식비를 비용으로 청구했다면 직원이 청구한 식비를 총계에 더한다. 식비를 비용으로 청구하지 않은 경우, 일일 기본 식비를 총계에 더한다.<br>
여기 있는 예외는 로직을 따라가기 어렵게 만든다. special case를 처리할 필요가 없다면 아래처럼 간결한 코드가 될 것이다.

```
MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
m_total += expenses.getTotal();
```

=> **Special Case Pattern**을 이용하자!

ExpenseReportDAO를 고쳐 언제나 MealExpenses를 반환하도록 하자

- 수정 전

```
class ExpenseReportDAO{
    MealExpenses getMeals(int employeeID) {
        ...
        if (meals are expensed)
            return a MealExpenses object
        else
            throw MealExpensesNotFound;
    }
    ...
}
```

- 수정 후

```
class ExpenseReportDAO{
    MealExpenses getMeals(int employeeID) {
        ...
        if (meals are expensed)
            return a MealExpenses object
        else
            return a PerDiemMealExpenses object
    }
    ...
}
```

```
public class PerDiemMealExpenses extends MealExpenses {
    public int getTotal() {
        // per diem default 리턴
    }
}
```

PerDiemMealExpenses는 MealExpenses의 subclass로, special case를 처리하기 위해 만든 클래스이다.<br>
그 결과, 아래와 같이 간결하게 작성할 수 있다.

```
MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
m_total += expenses.getTotal();
```

- meal expenses가 있다면, MealExpenses.getTotal()이 호출될 것이다. (normal flow)
- meal expenses가 없다면, PerDiemMealExpenses.getTotal()이 호출될 것이다. (special case)

정리하면, Special Case Pattern은 throw exception 대신 잘못된 경우를 처리하는 subclass를 만들어 special case를 처리하는 방식이다. 그러면 객체가 예외적인 상황을 캡슐화에서 처리하므로 코드에서 예외적인 상황을 처리할 필요가 없어진다.

### null을 반환하지 마라

- bad code 예시

```java
public void registerItem(Item item) {
    if (item != null) {
        ItemRegistry registry = peristentStore.getItemRegistry();
        if (registry != null) {
            Item existing = registry.getItem(item.getID());
            if (existing.getBillingPeriod().hasRetailOwner()) {
                existing.register(item);
            }
        }
    }
}
```

이 예시는 null check가 많아 코드가 지저분해 보인다. 심지어 existing에 대한 null check가 빠져있다. 만약 existing이 null이라면, NullPointerException이 발생할 것이다.<br>
이처럼 null을 리턴하는 함수는 호출자에게 문제를 떠넘긴다.<br>
이를 해결하기위해 special case 객체를 반환할 수 있다. 아래는 이것을 사용하여 개선하는 예시이다.

```java
List<Employee> employees = getEmployees();
if (employees != null) {
    for(Employee e : employees) {
        totalPay += e.getPay();
    }
}
```

`getEmployees()`는 null도 반환한다. 하지만 반드시 null을 반환할 필요가 있을까?

```java
List<Employee> employees = getEmployees();
if (employees != null) {
    for(Employee e : employees) {
        totalPay += e.getPay();
    }
}
```

```java
public List<Employee> getEmployees() {
    ...
    if ( ... there are employees ... )
        return employees;
    else if ( ... there are no employees ... )
        return Collections.emptyList();
}
```

이처럼 `getEmployees()`를 변경해 empty list를 반환할 경우 코드가 훨씬 깔끔해진다.<br>
이렇게 코드를 변경하면 NullPointerException이 발생할 가능성도 줄어든다.

### null을 전달하지 마라

메소드에서 null을 반환하는 것도 나쁘지만, 메서드로 null을 전달하는 것은 더 나쁘다.<br>

```java
public class MetricsCalculator
{
    public double xProjection(Point p1, Point p2) {
        return (p2.x – p1.x) * 1.5;
    }
    ...
}
```

누군가 인수로 null을 전달한다면 당연히 NullPointerException이 발생한다. 고치기 위해 아래처럼 새로운 exception 유형을 만들어 throw하는 방법이 있다.

```java
public class MetricsCalculator
{
    public double xProjection(Point p1, Point p2) {
        if (p1 == null || p2 == null) {
            throw InvalidArgumentException(
            "Invalid argument for MetricsCalculator.xProjection");
        }
        return (p2.x – p1.x) * 1.5;
    }
}
```

하지만 이 코드는 InvalidArgumentException을 잡아내는 handler가 필요하다. <br>
호출자가 실수로 넘기는 null을 적절하게 처리하는 방법은 거의 없다. 애초에 null을 넘기지 못하도록 하는 것이 낫다.

=> null을 주지도 말고, 받지도 말자
